#----------------------------------------------------------------------------
#       Make Workspace
#
# 
#
# This file was generated by MPC.  Any changes made directly to
# this file will be lost the next time it is generated.
#
# MPC Command:
# mwc.pl -type make knight.mwc
#
#----------------------------------------------------------------------------


all: Knight

depend: Knight-depend

clean generated realclean check-syntax $(CUSTOM_TARGETS):
	@$(MAKE) -f Makefile.Knight $(@)

.PHONY: Knight
Knight:
	@$(MAKE) -f Makefile.Knight all

.PHONY: Knight-depend
Knight-depend:
	@$(MAKE) -f Makefile.Knight depend

project_name_list:
	@echo Knight
